### ISSUE TITLE
Liste möglicher Fragmente

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mfragment#1]
- [ ] Cards (aus forhtml)
- [ ] Comment
- [ ] Container
- [ ] Description list
- [ ] Dropdown
- [ ] Form
- [ ] Gallery (aus forhtml)
- [ ] Image
- [ ] Lightbox
- [ ] Modal
- [ ] Nav
- [ ] Navbar
- [ ] Pagination
- [ ] Section
- [ ] Slider
- [ ] Slideshow
- [ ] Tabs and Accordion (aus forhtml)
- [ ] Video

Könnte auch ein einziges Fragment sein
- [ ] Image
- [ ] Lightbox
- [ ] Video
- [ ] Linked Media?

**Comment by joachimdoerr** [comment]
Default HTML Fragments: 

- [x] [Figure](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)
- [x] [Figcaption](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption)
- [ ] [Details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)
- [ ] [Dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
- [ ] [Iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)
- [x] [Img](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)
- [ ] [Picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
- [x] [Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source)
- [x] [Video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)
- [x] [Audio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio)
- [x] [Blockquote](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)
- [x] Generisches Tag Fragment

**Comment by joachimdoerr** [comment]
wegen geändertem Konzept obsolet.
